service: telegram-bot

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  stage: demo
  profile: personal
  runtime: nodejs10.x
  environment:
    ENV_NAME: ${self:custom.stage}
    LEX_BOT_ALIAS: ${self:custom.environment.LEX_BOT_ALIAS}
    LEX_BOT_NAME: ${self:custom.environment.LEX_BOT_NAME}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - "lex:PostText"
      Resource:
        - ${self:custom.lexBotArn}

custom:
  stage: ${opt:stage, self:provider.stage}
  environment: ${file(env.yml):${self:custom.stage}}
  lexBotArn:
    Fn::Join:
      - ":"
      - - arn
        - aws
        - lex
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - bot
        - ${self:custom.environment.LEX_BOT_NAME}
        - ${self:custom.environment.LEX_BOT_ALIAS}

functions:
  telegram-webhook:
    handler: lambdas/webhook.handler
    events:
      - http:
          path: telegram/webhook
          method: post   
