service: meme-bot

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  stage: demo
  profile: personal
  runtime: nodejs10.x
  environment:
    ENV_NAME: ${self:custom.stage}
    LEX_BOT_ALIAS: ${self:custom.environment.LEX_BOT_ALIAS}
    LEX_BOT_NAME: ${self:custom.environment.LEX_BOT_NAME}
    IMGFLIP_USERNAME: ${self:custom.environment.IMGFLIP_USERNAME}
    IMGFLIP_PASSWORD: ${self:custom.environment.IMGFLIP_PASSWORD}
    DYNAMODB_TABLE: ${self:service}-${self:custom.stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lex:PostText"
      Resource:
        - ${self:custom.lexBotArn}
    - Effect: "Allow"
      Action:
        - "translate:TranslateText"
        - "comprehend:DetectDominantLanguage"
      Resource: "*"

custom:
  stage: ${opt:stage, self:provider.stage}
  environment: ${file(env.yml):${self:custom.stage}}
  lexBotArn:
    Fn::Join:
      - ":"
      - - arn
        - aws
        - lex
        - Ref: AWS::Region
        - Ref: AWS::AccountId
        - bot
        - ${self:custom.environment.LEX_BOT_NAME}
        - ${self:custom.environment.LEX_BOT_ALIAS}

functions:
  telegram-webhook:
    handler: src/webhook.handler
    events:
      - http:
          path: telegram/webhook
          method: post

  meme-generator:
    handler: src/lex/meme-generator.handler
    environment:
      IMGFLIP_USERNAME: ${self:custom.environment.IMGFLIP_USERNAME}
      IMGFLIP_PASSWORD: ${self:custom.environment.IMGFLIP_PASSWORD}
